import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import { signedAnnouncementUrl } from './lib/announcementManagement'

function formatDate(value) { return value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not set' }
function Notice({ children, type = 'error' }) { return children ? <div className={`student-notice ${type}`} role="alert">{children}</div> : null }
export default function StudentAnnouncementsPage() { const navigate = useNavigate(); const [items, setItems] = useState([]); const [reads, setReads] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [profile, setProfile] = useState(null)
  async function load() { if (!isSupabaseConfigured || !supabase) return setError(true); try { await supabase.rpc('publish_due_announcements'); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return navigate('/student/login', { replace: true }); const profileResult = await supabase.from('student_profiles').select('id,full_name,student_code').eq('auth_user_id', auth.user.id).maybeSingle(); if (profileResult.error || !profileResult.data) throw profileResult.error || new Error('profile_missing'); const [announcementResult, readResult] = await Promise.all([supabase.from('announcements').select('id,title,content,status,published_at,created_at,announcement_targets(target_type,grade,educational_system,course_id,student_id),announcement_attachments(id,storage_path,file_name,file_type)').order('published_at', { ascending: false }), supabase.from('announcement_reads').select('announcement_id,read_at').eq('student_id', profileResult.data.id)]); if (announcementResult.error || readResult.error) throw announcementResult.error || readResult.error; setProfile(profileResult.data); setItems(announcementResult.data || []); setReads(readResult.data || []); setError(false) } catch { setError(true) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function open(item) { setSelected(item); if (!reads.some((read) => read.announcement_id === item.id)) { const { data } = await supabase.rpc('mark_announcement_read', { requested_announcement_id: item.id }); if (data) setReads((current) => [...current, data]) } }
  if (loading) return <div className="student-loading"><div className="payment-loader" /><p>Loading announcements...</p></div>
  if (error) return <div className="student-loading"><Notice>Unable to load announcements right now. <button onClick={load}>Try Again</button></Notice></div>
  const unread = items.filter((item) => !reads.some((read) => read.announcement_id === item.id))
  return <div className="student-area"><aside className="student-sidebar"><div className="student-side-brand"><Link to="/student/dashboard">ENGLISH <em>ZONE</em></Link><small>Student Area</small></div><div className="student-mini-profile"><div className="student-avatar">{profile?.full_name?.slice(0, 2).toUpperCase()}</div><div><strong>{profile?.full_name}</strong><small>{profile?.student_code}</small></div></div><nav className="student-nav"><Link to="/student/dashboard"><span className="nav-symbol">D</span>Dashboard</Link><Link to="/student/announcements" className="active"><span className="nav-symbol">A</span>Announcements</Link><Link to="/student/notifications"><span className="nav-symbol">N</span>Notifications</Link></nav></aside><div className="student-content"><header className="student-topbar"><Link className="topbar-code" to="/student/dashboard">← Dashboard</Link><div><span className="student-top-eyebrow">ENGLISH ZONE / ANNOUNCEMENTS</span><strong>{profile?.full_name}</strong></div></header><main className="student-main"><section className="student-page-section"><div className="student-page-heading"><div><span className="student-eyebrow">STAY UPDATED</span><h1>Announcements</h1><p>{unread.length} unread announcement{unread.length === 1 ? '' : 's'}</p></div></div>{items.length ? <div className="student-announcement-list">{items.map((item) => { const isRead = reads.some((read) => read.announcement_id === item.id); return <button className={`student-announcement-card ${isRead ? '' : 'unread'}`} key={item.id} onClick={() => open(item)}><span className="announcement-unread-dot" /><div><strong>{item.title}</strong><p>{item.content.slice(0, 150)}{item.content.length > 150 ? '...' : ''}</p><small>{formatDate(item.published_at)}</small></div></button> })}</div> : <div className="student-empty"><span>◇</span><p>No announcements yet.</p></div>}</section></main></div>{selected && <StudentAnnouncementModal item={selected} onClose={() => setSelected(null)} />}</div> }
function StudentAnnouncementModal({ item, onClose }) { const [url, setUrl] = useState(''); const attachment = item.announcement_attachments?.[0]; useEffect(() => { if (attachment) signedAnnouncementUrl(attachment.storage_path).then(setUrl).catch(() => setUrl('')) }, [attachment]); return <div className="student-modal-backdrop"><section className="student-modal student-announcement-modal" role="dialog" aria-modal="true"><div className="student-modal-heading"><div><span className="student-eyebrow">ANNOUNCEMENT</span><h2>{item.title}</h2></div><button onClick={onClose} aria-label="Close announcement">×</button></div><p className="student-announcement-content">{item.content}</p><small>{formatDate(item.published_at)}</small>{url && <a className="announcement-attachment-link" href={url} target="_blank" rel="noreferrer">Open {attachment.file_name} ↗</a>}</section></div> }
