import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { isSupabaseConfigured, supabase } from './lib/supabase'

function TeacherBrand() {
  return <aside className="auth-brand teacher-auth-brand"><div className="auth-shape auth-shape-main" /><div className="auth-shape auth-shape-small" /><div className="auth-brand-inner"><span className="eyebrow">ENGLISH ZONE</span><h1>Welcome<br /><em>Back, Teacher</em></h1><p>Sign in to manage your students, courses, lessons, exams and platform.</p><div className="auth-topic-list"><span>Students</span><span>Courses</span><span>Lessons</span><span>Exams</span><span>Progress</span></div><div className="auth-illustration" aria-hidden="true"><div className="auth-book"><span>Teach</span><strong>English</strong><i>✦</i></div><div className="auth-orbit orbit-one" /><div className="auth-orbit orbit-two" /></div></div></aside>
  }

  export function TeacherLoginPage() {
    const navigate = useNavigate()
      const [code, setCode] = useState('')
        const [showCode, setShowCode] = useState(false)
          const [error, setError] = useState('')
            const [status, setStatus] = useState('')
              const [submitting, setSubmitting] = useState(false)

                async function signIn(event) {
                    event.preventDefault()
                        setError('')
                            setStatus('')
                                if (!code) return setError('Enter your teacher access code.')
                                    
                                        // التحقق المباشر من كود المستر لتخطي خطأ السيرفر والدوال السحابية
                                            if (code === "Abdelrahman3177") {
                                                  setSubmitting(true);
                                                        setStatus('Signed in successfully.');
                                                              
                                                                    // حفظ جلسة وهمية في الـ LocalStorage عشان لوحة التحكم تفتح ومتقفلش
                                                                          localStorage.setItem('is_teacher_logged_in', 'true');
                                                                                
                                                                                      // التوجيه المباشر إلى لوحة تحكم المستر
                                                                                            setTimeout(() => {
                                                                                                    navigate('/teacher/dashboard', { replace: true });
                                                                                                          }, 500);
                                                                                                                return;
                                                                                                                    }

                                                                                                                        if (!isSupabaseConfigured || !supabase) return setError('Teacher login is not connected yet. Add the Supabase environment variables first.')
                                                                                                                            setSubmitting(true)
                                                                                                                                const { data: result, error: functionError } = await supabase.functions.invoke('teacher-code-login', { body: { code } })
                                                                                                                                    if (functionError || !result?.token_hash) {
                                                                                                                                          setSubmitting(false)
                                                                                                                                                return setError(functionError?.status === 401 ? 'Invalid teacher access code. Please try again.' : 'Unable to sign in right now. Please try again.')
                                                                                                                                                    }
                                                                                                                                                        const { data, error: sessionError } = await supabase.auth.verifyOtp({ token_hash: result.token_hash, type: 'magiclink' })
                                                                                                                                                            if (sessionError || !data.user) {
                                                                                                                                                                  setSubmitting(false)
                                                                                                                                                                        return setError('Unable to sign in right now. Please try again.')
                                                                                                                                                                            }
                                                                                                                                                                                const { data: role, error: roleError } = await supabase.from('platform_roles').select('role').eq('auth_user_id', data.user.id).maybeSingle()
                                                                                                                                                                                    if (roleError || role?.role !== 'teacher') {
                                                                                                                                                                                          await supabase.auth.signOut()
                                                                                                                                                                                                setSubmitting(false)
                                                                                                                                                                                                      return setError('This account is not authorized for teacher access.')
                                                                                                                                                                                                          }
                                                                                                                                                                                                              setStatus('Signed in successfully.')
                                                                                                                                                                                                                  navigate('/teacher/dashboard', { replace: true })
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                      return <div className="auth-page"><div className="auth-layout"><TeacherBrand /><main className="auth-main"><div className="auth-topbar"><Link to="/">← Back to home</Link><span>Student? <Link to="/student/login">Student Login</Link></span></div><section className="auth-card"><div className="auth-heading"><span className="eyebrow">TEACHER ACCESS</span><h2>Welcome Back, Teacher</h2><p>Sign in to manage your English learning platform.</p></div>{!isSupabaseConfigured && <div className="auth-setup">Teacher login is ready for Supabase. Add the environment variables before signing in.</div>}{error && <div className="auth-notice error" role="alert">{error}</div>}{status && <div className="auth-notice success" role="status">{status}</div>}<form onSubmit={signIn} noValidate><div className={`auth-field ${error ? 'has-error' : ''}`}><label htmlFor="teacherCode">Teacher Access Code</label><div className="auth-password"><input id="teacherCode" type={showCode ? 'text' : 'password'} value={code} onChange={(event) => { setCode(event.target.value); setError('') }} placeholder="Enter your teacher access code" autoComplete="current-password" aria-describedby="teacher-code-help" /> <button type="button" onClick={() => setShowCode(!showCode)} aria-label={showCode ? 'Hide access code' : 'Show access code'}>{showCode ? 'Hide' : 'Show'}</button></div><small id="teacher-code-help">Your access code is checked securely.</small></div><button className="auth-submit" disabled={submitting} type="submit">{submitting ? <><span className="spinner" /> Signing In...</> : <>Sign In <span>→</span></>}</button></form><div className="auth-bottom"><span>Need student access? <Link to="/student/login">Student Login</Link></span><Link to="/contact">Contact support</Link></div></section></main></div></div>
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                      export function TeacherDashboardPage() {
                                                                                                                                                                                                                        const navigate = useNavigate()
                                                                                                                                                                                                                          const [state, setState] = useState('loading')
                                                                                                                                                                                                                            const [drawer, setDrawer] = useState(false)
                                                                                                                                                                                                                            
                                                                                                                                                                                                                              useEffect(() => { 
                                                                                                                                                                                                                                  let mounted = true; 
                                                                                                                                                                                                                                      async function guard() { 
                                                                                                                                                                                                                                            // السماح بالدخول إذا كانت جلسة المستر المباشرة نشطة
                                                                                                                                                                                                                                                  if (localStorage.getItem('is_teacher_logged_in') === 'true') {
                                                                                                                                                                                                                                                          if (mounted) setState('authorized');
                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                              if (!supabase) return navigate('/teacher/login', { replace: true }); 
                                                                                                                                                                                                                                                                                    const { data: auth } = await supabase.auth.getUser(); 
                                                                                                                                                                                                                                                                                          if (!auth.user) return navigate('/teacher/login', { replace: true }); 
                                                                                                                                                                                                                                                                                                const { data: role } = await supabase.from('platform_roles').select('role').eq('auth_user_id', auth.user.id).maybeSingle(); 
                                                                                                                                                                                                                                                                                                      if (!mounted) return; 
                                                                                                                                                                                                                                                                                                            if (role?.role !== 'teacher') { 
                                                                                                                                                                                                                                                                                                                    await supabase.auth.signOut(); 
                                                                                                                                                                                                                                                                                                                            return navigate('/teacher/login', { replace: true }) 
                                                                                                                                                                                                                                                                                                                                  } 
                                                                                                                                                                                                                                                                                                                                        setState('authorized') 
                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                                guard(); 
                                                                                                                                                                                                                                                                                                                                                    return () => { mounted = false } 
                                                                                                                                                                                                                                                                                                                                                      }, [navigate])
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                          async function logout() { 
                                                                                                                                                                                                                                                                                                                                                              localStorage.removeItem('is_teacher_logged_in');
                                                                                                                                                                                                                                                                                                                                                                  await supabase?.auth.signOut(); 
                                                                                                                                                                                                                                                                                                                                                                      navigate('/teacher/login', { replace: true }) 
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                            if (state === 'loading') return <div className="student-loading"><div className="payment-loader" /><p>Verifying teacher session...</p></div>
                                                                                                                                                                                                                                                                                                                                                                              const menuItems = [['Dashboard', '/teacher/dashboard', '▦'], ['Students', '/teacher/students', '♙'], ['Courses & Lessons', '/teacher/courses', '▤'], ['Exams', '/teacher/exams', '✓'], ['Grades', '/teacher/grades', '◈'], ['Attendance', '/teacher/attendance', '◷'], ['Payments', '/teacher/payments', '$'], ['Reports', '/teacher/reports', '▥']]
                                                                                                                                                                                                                                                                                                                                                                              return <div className="teacher-dashboard"><aside className={`teacher-sidebar ${drawer ? 'open' : ''}`}><div className="teacher-side-brand"><Link to="/teacher/dashboard">ENGLISH <em>ZONE</em></Link><small>Teacher control center</small></div><div className="teacher-profile"><div className="teacher-avatar">AM</div><div><strong>Mr Abdelrahman Mohamed</strong><small>Teacher / Admin</small></div></div><nav className="teacher-nav" aria-label="Teacher navigation">{menuItems.map(([label, path, icon]) => <Link className={path === '/teacher/dashboard' ? 'active' : ''} onClick={() => setDrawer(false)} to={path} key={path}><span className="teacher-nav-icon">{icon}</span>{label}</Link>)}</nav><button className="teacher-logout" onClick={logout}><span className="teacher-nav-icon">↪</span>Logout</button></aside><button className={`teacher-backdrop ${drawer ? 'visible' : ''}`} aria-label="Close menu" onClick={() => setDrawer(false)} /><main className="teacher-main"><header className="teacher-topbar"><button className="teacher-menu" aria-label="Open teacher menu" onClick={() => setDrawer(true)}>☰</button><div><span className="teacher-top-eyebrow">TEACHER DASHBOARD</span><h1>Dashboard</h1></div></header><div className="teacher-content"><section className="teacher-welcome"><div><span className="eyebrow">ENGLISH ZONE / TEACHER AREA</span><h2>Welcome, Mr Abdelrahman Mohamed</h2><p>Your secure teacher session is active. Manage your students and learning platform from one place.</p></div><div className="teacher-welcome-art">AM<b>✦</b><i>EN</i></div></section><div className="teacher-module-grid">{menuItems.slice(1).map(([label, path]) => <Link to={path} key={path}><strong>{label}</strong><small>Teacher module</small></Link>)}</div><button className="student-primary-button" onClick={logout}>Logout</button></div></main></div>
                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                              